### ISSUE TITLE
react-scripts 3.3.0 versioning in packages.json breaks application

### ISSUE THREAD

**Issue by modeftron** [joetex/stream-racing-wheel#1]
A recent upgrade to dependencies with react-scripts 3.3.1 breaks the build while using 'yarn start' producing the following error: 

"TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined." 

Updating package.json from "react-scripts": "3.3.0" to "react-scripts": "^3.4.0" corrects the issue. 

More info on the react-scripts issue can be found here:
https://github.com/facebook/create-react-app/issues/8490

Great project BTW!

**Comment by joetex** [comment]
Thanks for the fix!  I will update the package.json!

**Comment by joetex** [comment]
Fixed!  I also had to fix the relative paths for each image.  gh-pages messed it up I guess.  All images needed to have the `/stream-racing-wheel/` path as their prefix.
