### ISSUE TITLE
Add additional button masks

### ISSUE THREAD

**Issue by Teriy-Aki** [joetex/stream-racing-wheel#10]
Heya, love the app! Is there a way to add additional button masks? I made myself custom icons for a fanatec wheel, and that wheel has more buttons than the G29. I would love to add more button masks so I can give the extra buttons a press indicator. Is that possible?

Thanks!

**Comment by joetex** [comment]
Which extra buttons does it have?

**Comment by Teriy-Aki** [comment]
Heya, I attached an image of the Wheel. As you can see, it also has additional L and R Buttons. The Buttons input properly in the app, they show up. The issue is that there are simply not enough button masks slots.

<img width="256" alt="wheel" src="https://github.com/joetex/stream-racing-wheel/assets/29336917/983c4a6d-2165-4f7c-a881-35797efa7134">

**Comment by joetex** [comment]
Can you show me what they show up as in the app?  Not sure of their internal names.

**Comment by joetex** [comment]
Hard refresh this page, I added L3 and R3, you should be able to rebind/reimage them:
https://joetex.github.io/stream-racing-wheel/
on windows: Ctrl+Shift+R
on mac: Cmd+Shift+R

**Comment by Teriy-Aki** [comment]
![image](https://github.com/joetex/stream-racing-wheel/assets/29336917/96c73e46-6c98-42c7-b18c-53560b78bca5)

Here is how the buttons are mapped in the app. Please Note that the Fanatec Wheel has 6 Additional Buttons (the pedals are their own) - So you would need to add L4 and R4 respectively. Otherwise it seems to work well!

Does this also work on the offline build?

**Comment by joetex** [comment]
holy crap, 31 inputs, xbox controller only goes up to 16.  
I'll add L4 and R4, but anymore than that, and I'll need to redesign how I coded it.

**Comment by joetex** [comment]
Yes, I pushed the changes for L3 and R3, just do a pull to get latest changes.

**Comment by joetex** [comment]
L4 and R4 are added now.  Refresh or pull latest changes.

**Comment by Teriy-Aki** [comment]
Works absolutely perfectly now! There is no need to map the rest of the buttons as they are on the back of the wheel and seldom used for anything. The existing bindings are enough for a shifter, pedals, and this wheel. You did a great job.

Thank you for the swift help and your amazing app!

**Comment by joetex** [comment]
There is a new section for Load Keybind Profile. Just select "Create new profile" from the dropdown, and start setting up your binds/images. Give the profile a name, then click "Create Profile" button.

It's setup to remember which profile you have selected once its created. You can edit the profile if you name it the same.

**Comment by joetex** [comment]
If you share the JSON, I can try to add it to the profile list in code.

**Comment by Teriy-Aki** [comment]
Sure, I would love to contribute. I have updated the app, re-binded my keys, and created a profile. Where exactly is the file with the custom profiles stored? I couldn't find it myself. I found KeybindProfiles.js, which seems to house the default button set, but I cannot find my custom ones. If you tell me where it is, I'll gladly share it with you.

**Comment by joetex** [comment]
When you select create new profile, it will show the JSON of current settings.  Just share that

**Comment by Teriy-Aki** [comment]
Alright. I attached a zip that includes the JSON strings in a text file + the images I created and adjusted for the custom profile. You're free to merge them if you like :)

[Fanatec.zip](https://github.com/joetex/stream-racing-wheel/files/14393403/Fanatec.zip)

**Comment by joetex** [comment]
It's saved to the localStorage of the browser, so it's all offline.
