### ISSUE TITLE
formatting/axis error

### ISSUE THREAD

**Issue by killerrosebud** [joetex/stream-racing-wheel#11]
okay so i'm wondering if there's any way to bind axis to buttons. i know it's a weird question, but my G29 isn't exactly like the wheel shown, and the D-Pad is an axis instead of buttons (also i have a few extra buttons i can't bind to the wheel cause they aren't there, and i can't find a good enough wheel picture to set it up with, nor do i think it'd actually work)

**Comment by joetex** [comment]
I'll work on this, its a big change, but I think it makes more sense.  I got most of it done, but it will require everyone to rebind everything.  
I'm thinking of also creating key bind profiles, so I can add the ones you all create for others to use, without having to rebind everything manually.

**Comment by killerrosebud** [comment]
sounds good! i'll keep an eye out for updates

**Comment by joetex** [comment]
alright, give it a shot.  You'll have to rebind all keys/images.  

There is a new section for `Load Keybind Profile`.  Just select "Create new profile" from the dropdown, and start setting up your binds/images.  Give the profile a name, then click "Create Profile" button.

It's setup to remember which profile you have selected once its created.  You can edit the profile if you name it the same.

**Comment by killerrosebud** [comment]
btw i'm shouting your name/visualizer from the mountaintops because of how dedicated you are to this project, and how friendly you've been with helping me over the years, if there's anything i can do for you, please let me know.
