### ISSUE TITLE
G923

### ISSUE THREAD

**Issue by ECENAT** [joetex/stream-racing-wheel#2]
Hi ... i'm using the G923. It works fine, but the pedals are worng mapped there. Any possibility to fix this? THx

**Comment by k1dm0rb1d** [comment]
Same I managed to change the wheel to Momo drifting one but I cannot sort out the pedals...

**Comment by joetex** [comment]
Hey guys, yea the current mapping is setup for G920.  You'd have to change the code to make it work for other wheels.

I didnt do a good job making it easy to map buttons, but its not too much code to fix.  I'm busy on other projects, so if anyone does a PR I would accept it.

**Comment by jandae** [comment]
For anyone trying to make it work with the g27
Important things:
- flatstore should be exactly be version 1.0.2 (don't know why it got the newest)
- shifter indices:
          gear1={8}
          gear2={9}
          gear3={10}
          gear4={11}
          gear5={12}
          gear6={13}
-break and accel pedals are combined
  - positive values is for break
  - negative values is for accel

I don't know react so took me a while to make it work

**Comment by JoTexas** [comment]
@jandae @ECENAT @k1dm0rb1d 

I have updated the GitHub Pages to allow Binding Inputs and Changing Images
https://joetex.github.io/stream-racing-wheel/

Please test.  Thanks!

**Comment by joetex** [comment]
@jandae @ECENAT @k1dm0rb1d 

I have updated the GitHub Pages to allow Binding Inputs and Changing Images
https://joetex.github.io/stream-racing-wheel/

Please test.  Thanks!
