### ISSUE TITLE
G29

### ISSUE THREAD

**Issue by apolation** [joetex/stream-racing-wheel#3]
I'm using Logitech G29 it's work fine, but, the pedals mapping is wrong for me: Gas is break, break is clutch pedal and the clutch is gas pedal, there's something that I can't change here to work?
Thanks for you project.

**Comment by joetex** [comment]
@apolation 

I have updated the GitHub Pages to allow Binding Inputs and Changing Images
https://joetex.github.io/stream-racing-wheel/

Please test. Thanks!
