### ISSUE TITLE
help for run!

### ISSUE THREAD

**Issue by Paronirium** [joetex/stream-racing-wheel#4]
Hi Joetex! Awesome Work!
I can see the steering wheel in the development link, but the pedals on my g29 don't match and I want to edit the code to accommodate my needs.
My problem comes when trying to compile and run in node the code.
Could you tell me, step by step, from cloning your repository to local to running the program in developer mode? It would be a great help!
Best regards and thanks!

**Comment by joetex** [comment]
@Paronirium 

I have updated the GitHub Pages to allow Binding Inputs and Changing Images
https://joetex.github.io/stream-racing-wheel/

Please test. Thanks!

**Comment by Paronirium** [comment]
Is good! I can select my g29. But... pedals are bad.
I need start in Node, but i have a error to start...

> @Paronirium
> 
> Actualicé las páginas de GitHub para permitir vincular entradas y cambiar imágenes https://joetex.github.io/stream-racing-wheel/
> 
> Por favor prueba ¡Gracias!

**Comment by joetex** [comment]
Did you rebind the inputs at the bottom of page?

**Comment by joetex** [comment]
@Paronirium 
You don't have to build in node anymore.  Just use the github page:
https://joetex.github.io/stream-racing-wheel/

**Comment by Paronirium** [comment]
OK! Thx!!! Its Works!!!
Very Thankfull!!!

**Comment by joetex** [comment]
Share your stream, so I can check it out 😄
