### ISSUE TITLE
am i f***king stupid?

### ISSUE THREAD

**Issue by killerrosebud** [joetex/stream-racing-wheel#5]
i'm trying to use this program, locally, but "npm install" is an incomplete command to install shit, and trying to use the actual link as the install source can't find a file. i'm trying to get my G29 to work with this

**Comment by joetex** [comment]
What version of node are you using?  I'm on node@16.  

You should be able to do `npm install node@16 -g`  to go to that version.

As for the online version, you need to select your G29 from the dropdown, which will open up the input binding at the bottom.

**Comment by killerrosebud** [comment]
first off, i apologize for the half-ramble that's my post, i was INCREDIBLY drunk trying to get it to work

second, i managed to get it working on the online version, i'm trying to get the offline version to work, but i guess i don't really understand what i'm doing

**Comment by joetex** [comment]
> first off, i apologize for the half-ramble that's my post, i was INCREDIBLY drunk trying to get it to work
> 
> second, i managed to get it working on the online version, i'm trying to get the offline version to work, but i guess i don't really understand what i'm doing

No problem, glad it worked on online.  You only need the offline version if you want to customize the code.

**Comment by killerrosebud** [comment]
alright, i'll use the online version

one more thing: i guess this is kinda a feature request but is it possible at all to have a way to make the buttons on the wheel light up if pressed or anything?

for context: i stream American Truck Simulator on Twitch, and i'm always using the buttons on the wheel, instead of using it for like racing or something

**Comment by joetex** [comment]
Ok, so I found a way to add the button presses, please refresh the online version and set this::
![image](https://user-images.githubusercontent.com/1610876/190840275-3cdc14ad-3836-4bbf-93a8-0da31dd7d9bf.png)
