### ISSUE TITLE
i somehow have yet another issue

### ISSUE THREAD

**Issue by killerrosebud** [joetex/stream-racing-wheel#6]
I just recently had to rearrange my streaming setup and now running a two-PC setup, where i'm unable to use your visualizer for the racing wheel

i really like the visualizer, my chat loved it, and since it's web based, i was wondering if there was any way at the moment that i could somehow send the data from the browser on my gaming PC to the one on my streaming PC and use the visualizer again

the only interaction between the two computers is a video signal running from my gaming rig to the capture card on my streaming rig, so to my knowledge, anything physical/program-wise is out of the picture

also i feel bad cause you helped me get it all set up and working and now i can't use it lol

**Comment by acosg** [comment]
Try Chrome Remote Desktop, chrome has an extension for it, you can remote to the gaming rig from the streaming rig.  There are other programs that can do remote desktop, but chrome is easiest.

**Comment by killerrosebud** [comment]
chrome remote desktop doesn't exactly do what i need. i can show my desktop using the capture card. what i need is a way to show the exact window with racing wheel data on another chrome browser (or browsersource in OBS) while said window is in the background. i need to keep my VR view on top of everything, so remote desktop wouldn't really work for that, as i'd need to have the chrome window in the foreground

**Comment by joetex** [comment]
What if you try using OBS Studio on gaming rig just to capture the browser
window and stream it to the other PC via LAN, like this video explains
https://youtu.be/oc255vMSZLY

**Comment by killerrosebud** [comment]
that seems to be the way to solve it, unfortunately my version of OBS currently doesn't support that plugin. will hopefully have an update soon

**Comment by killerrosebud** [comment]
after doing a bit of work myself cause i was tired of waiting for the damn plugin to update for OBS, i just downgraded my OBS and now everything works amazingly!

thank you SO MUCH for bringing this to my attention, this has solved SO many issues i was having

**Comment by joetex** [comment]
> after doing a bit of work myself cause i was tired of waiting for the damn plugin to update for OBS, i just downgraded my OBS and now everything works amazingly!
> 
> thank you SO MUCH for bringing this to my attention, this has solved SO many issues i was having

Glad you got it working!
