### ISSUE TITLE
Feature Request: Invert pedal display

### ISSUE THREAD

**Issue by raidekoptix** [joetex/stream-racing-wheel#7]
Would it be possible to invert the display of pedal axis?

I've got the Logitech G29, and in it's idle state (nothing pressed), it looks fine, but as I press pedals, the icon moves down... I'd like the option for this to be inverted, where the icons start in their lowest position and move UP on-screen.

**Comment by joetex** [comment]
Done.  Added an invert toggle in the configuration for wheel/pedals.  

Please test and let me know if it works.  If you stream, feel free to share =)

**Comment by raidekoptix** [comment]
Worked perfectly. Thank you so much for this!
