### ISSUE TITLE
i cant use it on obs how to fix it the developermode link wont work for me how to fix it

### ISSUE THREAD

**Issue by KeanopcYT** [joetex/stream-racing-wheel#8]

**Comment by joetex** [comment]
@KeanopcYT  Which browser are you using?

**Comment by KeanopcYT** [comment]
I’m using chrome

**Comment by joetex** [comment]
I'm not sure what you mean by "won't work"?  Does the page not load at all?  Does it not detect your device?  Please provide more details.  Thanks

**Comment by KeanopcYT** [comment]
if i click on the host link it wont load it CANT REACH THE SITE

**Comment by joetex** [comment]
https://joetex.github.io/stream-racing-wheel/
This one?  It works for me, which country are you in?

**Comment by KeanopcYT** [comment]
Netherlands

**Comment by KeanopcYT** [comment]
How do I get this on obs can you make a Turtorial

**Comment by joetex** [comment]
In OBS you can create a view that looks at your screen or chrome window.  Then you configure its properties, cropping the view to show only the wheel / pedals.   Then you create a Filter called Color Key that matches the background color `#133A4D` , which will make the background transparent.
