### ISSUE TITLE
Remove background

### ISSUE THREAD

**Issue by danyrt** [joetex/stream-racing-wheel#9]
Hello,
Nice work! How can I remove the background and maybe select what exactly I want to stream between Shifter, Wheel, pedals?

**Comment by joetex** [comment]
For OBS:
If you need to remove an unwanted background from an existing source to make it transparent, right-click the source->Filters and add the chroma key filter (or color key filter, or luma key filter - depends on the nature of the background).

You can do multiple sources for each pedal or wheel or whatever and move them as needed.

**Comment by danyrt** [comment]
True, didn’t think of stream same source multiple times and cut..tnx, remove background is also working in obs, not working in tiktok studio but nevertheless.
